[config.custom_colors]
red = { color = "#ff0000", blend = true }
green = { color = "#00ff00", blend = true }
blue = { color = "#0000ff", blend = true }
yellow = { color = "#ffff00", blend = true }
orange = { color = "#ff9900", blend = true }
purple = { color = "#a020f0", blend = true }
cyan = { color = "#00ffff", blend = true }
magenta = { color = "#ff00ff", blend = true }

